site_name: docs/latest

plugins:
    - search

nav:
    - Concepts: concepts.md
    - User Guide:
          - deployment.md
          - bootstrap.md
          - configuration.md
          - storage.md
          - production.md
    - Security:
          - authorization.md
    - Contribute:
          - developer-guide.md
          - customize.md
